### ISSUE TITLE
Add gemeinde name as searchable detail to zipcodes

### ISSUE THREAD

**Issue by gjn** [geoadmin/service-sphinxsearch#193]
See discussion https://github.com/geoadmin/mf-geoadmin3/issues/2160

Add langtext (commune name) to detail https://github.com/geoadmin/service-sphinxsearch/blob/master/conf/search.conf.part#L151

@ponceta Could you do it?

**Comment by ponceta** [comment]
Yes, sure!

**Comment by ponceta** [comment]
![image](https://cloud.githubusercontent.com/assets/8614223/6243562/2513ab9e-b744-11e4-9206-1bf3ffba1eed.png)

Big communes (Like Bern, Lausanne, ... ) have to many zipcodes to be displayed in the search bar.

**Comment by ponceta** [comment]
This was left off as the result was not satisfying (NPA results were overcrowding the results)
