### ISSUE TITLE
get rid of soundex fuzzy index

### ISSUE THREAD

**Issue by ltclm** [geoadmin/service-sphinxsearch#244]

**Comment by gjn** [comment]
Why?

**Comment by ltclm** [comment]
its just a reminder, we should decide which fuzzy index we would like to keep. actually we have soundex (english) and metaphone...

**Comment by ltclm** [comment]
@davidoesch could you please decide which fuzzy index we should keep. 
both are overkill and are slowing down database deploy.

**Comment by davidoesch** [comment]
Which one is triggered / used more often now?

**Comment by ltclm** [comment]
We cant extract this information from the logfiles.
A detailed comparison can be found [here](http://www.informit.com/articles/article.aspx?p=1848528).
The soundex hash always takes the first letter and converts the following consonants into digits, the hash has 4 characters:
```python

#!/usr/bin/env python

import fuzzy

names = [ 'Brigmattenweg', 'Brig', 'Birgmattenweg', 'Brieg',
          'Banhof', 'Bahnhof',
          'Strasse', 'Strase',
          'Samichlaus', 'Samiklaus'
          ]

soundex = fuzzy.Soundex(4)

for n in names:
    print '%-20s' % n, soundex(n)

$  python soundex.py
Brigmattenweg        B625
Brig                 B620
Birgmattenweg        B625
Brieg                B620
Banhof               B510
Bahnhof              B510
Strasse              S362
Strase               S362
Samichlaus           S524
Samiklaus            S524
```

The metaphone algorithm is more complex and generates hashes of a variable length:
```python
#!/usr/bin/env python

import fuzzy

names = [ 'Brigmattenweg', 'Brig', 'Birgmattenweg', 'Brieg',
          'Banhof', 'Bahnhof',
          'Strasse', 'Strase',
          'Samichlaus', 'Samiklaus'
          ]

dmetaphone = fuzzy.DMetaphone(4)

for n in names:
    print '%-20s' % n, dmetaphone(n)[0]

$ python metaphone.py
Brigmattenweg        PRKM
Brig                 PRK
Birgmattenweg        PRKM
Brieg                PRK
Banhof               PNF
Bahnhof              PNF
Strasse              STRS
Strase               STRS
Samichlaus           SMXL
Samiklaus            SMKL
```

Both alogrithm are based on english pronunciation thats the common disadvantage. 

But i would keep the metaphone index.

**Comment by davidoesch** [comment]
decision: keep metaphone index delete soundex

**Comment by ltclm** [comment]
thanks for the feedback @davidoesch 
@gjin do you agree, i can prepare a pr.

**Comment by gjn** [comment]
Of all swissearch requests, 20% touch the fuzzy indices (currently soundex and metaphone). https://logs.bgdi.ch/kibana/#/dashboard/elasticsearch/swisssearch. For 80% of all searches, this change has not impact.

For the other 20%, the change could be analysed in detail, but I suspect for your use case (short terms generally), the differences between soundex and metaphone is small (as can be seen in @ltclm example).

**Comment by gjn** [comment]
There is a difference of results.
**Term: wasss**
With soundex:
![image](https://cloud.githubusercontent.com/assets/2572317/14504373/db023612-01b4-11e6-98c9-759a6c027c2f.png)

Without soundex:
![image](https://cloud.githubusercontent.com/assets/2572317/14504399/f284f37e-01b4-11e6-989c-ea22d3cbffa4.png)

**term: randlses**
With soundex:
![image](https://cloud.githubusercontent.com/assets/2572317/14504424/13bd5694-01b5-11e6-9f6f-893dea22be7d.png)

Without soundex
![image](https://cloud.githubusercontent.com/assets/2572317/14504456/304e700e-01b5-11e6-8f4e-10cc48e10cdc.png)

**term: rue de morque**
With soundex:
![image](https://cloud.githubusercontent.com/assets/2572317/14504534/884c0230-01b5-11e6-8afc-5ea4b31d6084.png)


Without soundex:
![image](https://cloud.githubusercontent.com/assets/2572317/14504524/7ac1215e-01b5-11e6-8ea1-c7931a48e511.png)

**Comment by davidoesch** [comment]
Thanks Gilbert for the examples.   key here- both algorithms do work fairly well for English terms.... But do have mediocre result for DE FR IT.  The original use case was two fold: give the user a feedback if he made a small typo (zrich wassser etc)- here we do already fail but give at least some ideas  /proposals. The second use case was to detect use cases like hallenstadion which is in our DB as Hallen Stadion ... And vice versa. Here we fail completely. Even after two years having this request open: there is no free algorithm available for this to my knowledge

**Comment by gjn** [comment]
We simply didn't invest any resource into improving the search for such cases. Other things have higher priority.

I'm convinced we could improve the situation.
