### ISSUE TITLE
Gazetter - additional attributes

### ISSUE THREAD

**Issue by gjn** [geoadmin/service-sphinxsearch#281]
Gazetter as a couple of different sources of their data. I think we should an attributes to gazetter indices:
- type (object type token describing the type of object)

Thoughts?

**Comment by gjn** [comment]
ping @ltclm 

Could you have a look for this?

**Comment by ltclm** [comment]
We already have the ``origin`` attribute in the index, 
we could extent this to
* gazetter.haltestellen
* gazetter.dkm10
* etc.

**Comment by gjn** [comment]
Better to add a new attribute - otherwise, we might break existing applications (origins is officially documented).

'type' of something.

**Comment by davidoesch** [comment]
ping @gjn
