### ISSUE TITLE
pg2sphinx_trigger should be more robust...

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/service-sphinxsearch#297]
For instance with https://github.com/geoadmin/service-sphinxsearch/pull/296
-> a column that doesn't exist -> no update of some sphinx indices

**Comment by gjn** [comment]
I think the trigger is exactly doing what needs to be done. Remember, we have a table update and the trigger needs to find the indices using this tables - so it needs to check _all_ incides and its queries. So when a query is wrong, then what? Just ignore the error and continue? What if the error is in the indice that needs the update?

I think it's good that a wrong sql query fails - we just need to be sure that we don't deploy such a thing and don't have a db deployed that would break and sql query. So if you agree, I'd rather do https://github.com/geoadmin/service-sphinxsearch/issues/298 and close this one.

**Comment by loicgasser** [comment]
Yes we can do both
