### ISSUE TITLE
Add integration test for sphinx configuration

### ISSUE THREAD

**Issue by gjn** [geoadmin/service-sphinxsearch#298]
We could use the EXPLAIN VERBOSE sql command to verify if the sql queries in the sphinx configuration are valid with the corresponding db's. Similar thing is done in the db trigger already: https://github.com/geoadmin/service-sphinxsearch/blob/master/deploy/pg2sphinx_trigger.py#L20

Such a test could be run
a) on PR requests (jenkins)
b) nightly (jenkins)
c) before deploying new sphinx configuration, deploy script
d) before deploying new dbs or db tables, deploy script

We could avoid troubles we had with wrong sql queries in the sphinx configuration that resulted in db triggers not working anymore.

@loicgasser @ltclm Thoughts?

**Comment by ltclm** [comment]
make move template is doing exactly this test.
see move-template.sh line 9.

**Comment by gjn** [comment]
Does that test the sql queries against the dbs?
Am 01.10.2016 11:12 vorm. schrieb Clausen Marcel <notifications@github.com>:make move template is doing exactly this test.
see move-template.sh line 9.

**Comment by ltclm** [comment]
yes,  it sends ``explain verbose + query`` to the db

**Comment by ltclm** [comment]
c)
make move template is already testing the queries in the dev environment. we could extent this test with int and prod environment queries.
d) what is more important / most used up-to-date tooltip or object search? i would not add this to the db deploy as pre deploy hook

**Comment by gjn** [comment]
That's fantastic then.

So we could use this for jenkins jobs and on deploy - and check against 
active dbs (and nightly for production).

Check seems fast, so this could be added to db deploy as well. As we saw 
with issue last week, a
wong SQL query in the sphinx config might cause failure for all 
auto-updates and other db triggers.

**Comment by loicgasser** [comment]
See my comment in https://github.com/geoadmin/service-sphinxsearch/pull/300

**Comment by loicgasser** [comment]
I would propose to trigger a test when on opens a PR. We should control:
1. That all the config are valid
2. That the referenced SQL queries are valid
3. That we have more than one item to reference for searchable layers

**Comment by ltclm** [comment]
good idea
test 1. and 2. are already in 
``make move-template``

The 3rd test should be done during data integration. We have indices which are empty  (sachplan)  and they can have 0..n features in it.

In which git hook do you propose to add tests 1 and 2?

**Comment by loicgasser** [comment]
I propose to do that using nose. We just need to split a couple of functions.

We have to configure Jenkins 2 and 3 are possible without have a sphinxserver on Jenkins instance, while 1 checkconfig is part of Sphinx if I am not mistaken.

**Comment by ltclm** [comment]
dont you think it would be better to use a pre-commit hook?

**Comment by loicgasser** [comment]
oh yes, that's doable as well.
That's how we do it in CHSDI.
https://github.com/geoadmin/mf-chsdi3/blob/master/Makefile#L340

You want to do it or shall I?

**Comment by ltclm** [comment]
i will try to do it.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/service-sphinxsearch/commit/94fefb9f5125312ca771c4ce2f786c490b6a249e

**Comment by ltclm** [comment]
can we close this? we have a pre-commit hook which is checking the sphinx config and all the queries with explain verbose.

**Comment by loicgasser** [comment]
I would say yes
