### ISSUE TITLE
Rank Ort higher than other gazetter entries

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/service-sphinxsearch#323]
We have this ranking rule test which is now failing because we add more info in the detail field.
https://github.com/geoadmin/service-sphinxsearch/pull/322

We want the objektart ORT from tlm.swissnames3d_poly to come before the rest of the so called gazetter origin.
To address this problem I propose to play on the rank. I'll propose a PR today.

======================================================================
FAIL: test_search_ranking (chsdi.tests.integration.test_search.TestSearchServiceView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/PR_chsdi3/chsdi/tests/integration/test_search.py", line 155, in test_search_ranking
    self.assertEqual(resp.json['results'][0]['attrs']['detail'], 'gstaad')
AssertionError: u'gstaad bdgag-lgw saanen' != 'gstaad'
-------------------- >> begin captured logging << --------------------
chsdi: DEBUG: route matched for url http://localhost/rest/services/ech/SearchServer?searchText=gstaad&type=locations; route_name: 'search', path_info: u'/rest/services/ech/SearchServer', pattern: '/rest/services/{map}/SearchServer', matchdict: {'map': u'ech'}, predicates: ''
chsdi: DEBUG: debug_authorization of url http://localhost/rest/services/ech/SearchServer?searchText=gstaad&type=locations (view name u'' against context <pyramid.traversal.DefaultRootFactory instance at 0x7f61d831ccf8>): Allowed (no authorization policy in use)
--------------------- >> end captured logging << ---------------------

**Comment by gjn** [comment]
Is this related to a front-end issue?

**Comment by loicgasser** [comment]
No ranking

**Comment by gjn** [comment]
@loicgasser What's the state?

**Comment by loicgasser** [comment]
It's done
