### ISSUE TITLE
Swisssearch: Silsersee not found

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/service-sphinxsearch#405]
ALL OS All Devices

Search for
"Silsersee" or " Lej da Segl"
Result not  found https://s.geo.admin.ch/839134d618 

Other RM Lakes like "lag la Cauma" or " Lag la Cresta " found but not DE "Crestasee" "Caumasee"

- [x] Bugfixing (see https://github.com/geoadmin/service-sphinxsearch/pull/414 )
- [ ] Lieferung DKM von ltclm an bov, Bov prüft
- [ ] bov prüft Mehrsprachigkeit

- [ ] Korrekte Lieferung an ltclm

**Comment by ltclm** [comment]
technical background:
https://github.com/geoadmin/service-sphinxsearch/pull/275

other stuff related to this:
https://github.com/geoadmin/mf-chsdi3/issues/3182
https://github.com/geoadmin/service-sphinxsearch/pull/397

**Comment by davidoesch** [comment]
- [ ] Bugfixing 
- Lieferung DKM von ltcm an bov, Bov prüft
- bov prüft Mehrsprachigkeit

- [ ] Korrekte Leiferung an ltcm

**Comment by davidoesch** [comment]
In der Zwischenzeit konnte ich mit der Hilfe von Raphael das Problem der Mehrsprachigkeit bei Seen etc. fixen. Bitte benutzt folgenden Testlink:
https://mf-chsdi3.dev.bgdi.ch/shorten/8601c35bbc

In der aktuellen (falschen) Version auf prod wird bei mehreren Treffern mit derselben UUID immer nur der erste Treffer indiziert. Das ist jetzt nicht mehr der Fall.
https://github.com/geoadmin/service-sphinxsearch/pull/414

**Comment by ltclm** [comment]
können wir das schliessen @davidoesch ?

**Comment by davidoesch** [comment]
Kann geschlossen werden.
All die Fälle oben funktionieren
